# Generated by Django 3.2.18 on 2023-04-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kichkintoy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_grop',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking_grop',
            name='group',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking_grop',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
